### ISSUE TITLE
travis log empty ... cannot debug why it fails ...

### ISSUE THREAD

**Issue by martin-raden** [BackofenLab/ExpaRNA#4]
Build log is empty and I have not idea why it is failing...

Could you please also enable travis builds for pull request. seems that this was not working too.

**Comment by bgruening** [comment]
PR builds are working, but the general setup with travis does not seem to start. Is IntaRNA travis working for you?

**Comment by bgruening** [comment]
Its a travis issue: https://www.traviscistatus.com/incidents/lp492hx0z1my
